title: The Hundred Saints
description: Fantasy RPG Wiki for dark ages inspired gaming.
# theme: just-the-docs

url: https://JumaJuiceTime.github.io/HundredSaints

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
